// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOeaoexqONYF9X4iRZ9GCqKlJo6JwROho',
    appId: '1:585076869199:android:0003d88bbe843fc505423a',
    messagingSenderId: '585076869199',
    projectId: 'ecommerce-a1e8f',
    storageBucket: 'ecommerce-a1e8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnXtJHLl5bAxtnV7O9rHf2HcnTMlv3ZvQ',
    appId: '1:585076869199:ios:1a627e0e766d0bf005423a',
    messagingSenderId: '585076869199',
    projectId: 'ecommerce-a1e8f',
    storageBucket: 'ecommerce-a1e8f.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  // This desktop target shares the registered Apple bundle identifier with iOS.
  // Re-run `flutterfire configure` if a separate macOS Firebase app is created.
  static const FirebaseOptions macos = ios;
}
